name: Anchor Unit Tests
on:
  push:
env:
  CARGO_TERM_COLOR: always
  TEST_TIMEOUT: 15000 #Required as solana local validator takes time
jobs:
  build:
    runs-on: ubuntu-latest
    container: backpackapp/build:v0.30.1

    steps:
      - uses: actions/checkout@v4

      - name: List rustup toolchains
        run: rustup toolchain list

      - name: Set default toolchain
        run: rustup default stable

      - name: Generate new keygen
        run: solana-keygen new --no-bip39-passphrase

      - name: Set solana target cluster to local
        run: solana config set --url http:localhost:8899

      - name: Check solana config
        run: solana config get

      - name: Install npm dependencies
        run: npm ci

      - name: Install anchor dependencies
        run: cd ./anchor && npm ci

      - name: Run tests with Bankrun
        run: npm run anchor-bankrun-test

      - name: Clean nx cache
        run: npx nx reset --only-cache

      - name: Run tests with Solana Local Validator
        run: npm run anchor-test
