name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0
        with:
          node-version: '23.x'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run anchor-bankrun-test
        env:
          CI: true
